### ISSUE TITLE
Not working for 3.5.8

### ISSUE THREAD

**Issue by TheApexDevil** [VforValens/AIO#7]
need explanation needed other then seems to be a abandoned mod looking at the download page comments so think its time to move it to a new dev or update it or end up like the official tarcov game down the drain

**Comment by VforValens** [comment]
Yeah, I don't really maintain the mod as Tarkov is no longer an interest of mine.

It's also not a mod that anyone can maintain due to my license as redistribution is not allowed so good luck with that one.
